name: 'Compress File'

description: 'compress specific suffix files under specific path'

inputs:
  file-suffix:
    description: 'file suffix'
    required: true
    default: 'pdf'
  target-directory-path:
    description: 'target directory path'
    required: true
    default: './'
  compress-tool:
    description: 'compress tool: gzip bzip2 zip'
    required: true
    default: 'gzip'

outputs:
  state:
    description: 'compress action state. \
                  0 : normal state  \
                  1 : commpress tool unsupport  \
                  2 : target directory path not exist'
  archive:
    description: 'compressed archive file'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-suffix }}
    - ${{ inputs.target-directory-path }}
    - ${{ inputs.compress-tool }}

branding:
  icon: archive
  color: purple
