name: Compress File

on: [push]

jobs:
  compress:
    runs-on: ubuntu-latest
    name: Compress files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress txt with gzip
        uses: coco-hkk/compress-action@master
        id: step1
        with:
          file-suffix: 'txt'
          target-directory-path: 'tes'
          compress-tool: 'gzip'
      - name: Get archive
        run: |
          if [ "0"x != "${{ steps.step1.outputs.state }}"x ]; then
            echo "archive create failed, exit"
          else
            tar -tzvf ${{ steps.step1.outputs.archive }}
          fi

      - name: Compress md with bzip2
        uses: ./
        id: step2
        with:
          file-suffix: 'md'
          target-directory-path: 'test'
          compress-tool: 'bzip'
      - name: Get archive
        run: |
          if [ "0"x != "${{ steps.step2.outputs.state }}"x ]; then
            echo "archive create failed, exit"
          else
            tar -tjvf ${{ steps.step2.outputs.archive }}
          fi

      - name: Compress tex with zip
        uses: ./
        id: step3
        with:
          file-suffix: 'tex'
          target-directory-path: 'test'
          compress-tool: 'zip'
      - name: decompress
        run: |
          if [ "0"x != "${{ steps.step3.outputs.state }}"x ]; then
            echo "archive create failed, exit"
          else
            unzip ${{ steps.step3.outputs.archive }}
          fi

      - name: Compress tex with brotli
        uses: ./
        id: step4
        with:
          file-suffix: 'tex'
          target-directory-path: 'test'
          compress-tool: 'brotli'

      - name: Install brotli
        run: |
          cd $HOME
          git clone https://github.com/google/brotli
          cd brotli

          mkdir out && cd out
          ../configure-cmake
          make

          cd $GITHUB_WORKSPACE

      - name: decompress
        run: |
          if [ "0"x != "${{ steps.step4.outputs.state }}"x ]; then
            echo "archive create failed, exit"
          else
            archive=${{ steps.step4.outputs.archive }}
            $HOME/brotli/out/brotli -d $archive
            ls -l
            sudo chown root:root ${archive%.*}
            ls -l
            tar -xf ${archive%.*}
          fi
