name: Compress File

on: [push]

jobs:
  compress:
    runs-on: ubuntu-latest
    name: Compress files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compress txt with gzip
        uses: ./
        id: step1
        with:
          file_type: 'txt'
          path: 'test'
          method: 'gzip'
      - name: Get archive
        run: |
          echo "archive : ${{ steps.step1.outputs.archive }}"
          tar -tzvf ${{ steps.step1.outputs.archive }}

      - name: Compress md with bzip2
        uses: ./
        id: step2
        with:
          file_type: 'md'
          path: 'test'
          method: 'bzip2'
      - name: Get archive
        run: |
          echo "archive : ${{ steps.step2.outputs.archive }}"
          tar -tjvf ${{ steps.step2.outputs.archive }}

      - name: Compress tex with zip
        uses: ./
        id: step3
        with:
          file_type: 'tex'
          path: 'test'
          method: 'zip'
      - name: Get compressed message
        run: |
          echo "archive : ${{ steps.step3.outputs.archive }}"
          unzip ${{ steps.step3.outputs.archive }}
