name: Compress File

on: [push]

jobs:
  compress:
    runs-on: ubuntu-latest
    name: Compress files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress txt with gzip
        uses: ./
        id: step1
        with:
          suffix: 'txt'
          path: 'tes'
          method: 'gzip'
      - name: Get archive
        run: |
          echo "archive : ${{ steps.step1.outputs.archive }}"

          if [ "0"x != "${{ env.error_value }}"x ]; then
            echo "archive create failed, exit"
          else
            tar -tzvf ${{ steps.step1.outputs.archive }}
          fi

      - name: Compress md with bzip2
        uses: ./
        id: step2
        with:
          suffix: 'md'
          path: 'test'
          method: 'bzip'
      - name: Get archive
        run: |
          echo "archive : ${{ steps.step2.outputs.archive }}"
          if [ "0"x != "${{ env.error_value }}"x ]; then
            echo "archive create failed, exit"
          else
            tar -tjvf ${{ steps.step2.outputs.archive }}
          fi

      - name: Compress tex with zip
        uses: ./
        id: step3
        with:
          suffix: 'tex'
          path: 'test'
          method: 'zip'
      - name: Get compressed message
        run: |
          echo "archive : ${{ steps.step3.outputs.archive }}"
          if [ "0"x != "${{ env.error_value }}"x ]; then
            echo "archive create failed, exit"
          else
            unzip ${{ steps.step3.outputs.archive }}
          fi
