name: file-archive-actions

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compress files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compress action step
        uses: ./
        with:
          file_type: 'tex'
          path: 'doc'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
